/**
 * YouTube Studio language selectors reviewed read-only on 2026-07-16.
 *
 * Studio selector membership owns inclusion here. The YouTube video resource
 * documents the stored fields, while i18nLanguages describes YouTube
 * application languages and is not the selector-membership authority:
 * https://developers.google.com/youtube/v3/docs/videos
 * https://developers.google.com/youtube/v3/docs/i18nLanguages
 */
export interface YouTubeLanguageOption {
  readonly value: string;
  readonly label: string;
}

const youTubeDefaultLanguageOption: YouTubeLanguageOption = Object.freeze({
  value: '',
  label: 'YouTube Default',
});

const youTubeSharedLanguageOptions: readonly YouTubeLanguageOption[] = Object.freeze(
  [
    Object.freeze({ value: 'ab', label: 'Abkhazian' }),
    Object.freeze({ value: 'aa', label: 'Afar' }),
    Object.freeze({ value: 'af', label: 'Afrikaans' }),
    Object.freeze({ value: 'ak', label: 'Akan' }),
    Object.freeze({ value: 'akk', label: 'Akkadian' }),
    Object.freeze({ value: 'sq', label: 'Albanian' }),
    Object.freeze({ value: 'ase', label: 'American Sign Language' }),
    Object.freeze({ value: 'am', label: 'Amharic' }),
    Object.freeze({ value: 'ar', label: 'Arabic' }),
    Object.freeze({ value: 'arc', label: 'Aramaic' }),
    Object.freeze({ value: 'hy', label: 'Armenian' }),
    Object.freeze({ value: 'frp', label: 'Arpitan' }),
    Object.freeze({ value: 'as', label: 'Assamese' }),
    Object.freeze({ value: 'ay', label: 'Aymara' }),
    Object.freeze({ value: 'az', label: 'Azerbaijani' }),
    Object.freeze({ value: 'bm', label: 'Bambara' }),
    Object.freeze({ value: 'bn', label: 'Bangla' }),
    Object.freeze({ value: 'bn-IN', label: 'Bangla (India)' }),
    Object.freeze({ value: 'ba', label: 'Bashkir' }),
    Object.freeze({ value: 'eu', label: 'Basque' }),
    Object.freeze({ value: 'be', label: 'Belarusian' }),
    Object.freeze({ value: 'bh', label: 'Bhojpuri' }),
    Object.freeze({ value: 'bi', label: 'Bislama' }),
    Object.freeze({ value: 'brx', label: 'Bodo' }),
    Object.freeze({ value: 'bs', label: 'Bosnian' }),
    Object.freeze({ value: 'br', label: 'Breton' }),
    Object.freeze({ value: 'bg', label: 'Bulgarian' }),
    Object.freeze({ value: 'my', label: 'Burmese' }),
    Object.freeze({ value: 'yue', label: 'Cantonese' }),
    Object.freeze({ value: 'yue-HK', label: 'Cantonese (Hong Kong)' }),
    Object.freeze({ value: 'ca', label: 'Catalan' }),
    Object.freeze({ value: 'chr', label: 'Cherokee' }),
    Object.freeze({ value: 'zh', label: 'Chinese' }),
    Object.freeze({ value: 'zh-CN', label: 'Chinese (China)' }),
    Object.freeze({ value: 'zh-HK', label: 'Chinese (Hong Kong)' }),
    Object.freeze({ value: 'zh-Hans', label: 'Chinese (Simplified)' }),
    Object.freeze({ value: 'zh-SG', label: 'Chinese (Singapore)' }),
    Object.freeze({ value: 'zh-TW', label: 'Chinese (Taiwan)' }),
    Object.freeze({ value: 'zh-Hant', label: 'Chinese (Traditional)' }),
    Object.freeze({ value: 'cho', label: 'Choctaw' }),
    Object.freeze({ value: 'cop', label: 'Coptic' }),
    Object.freeze({ value: 'co', label: 'Corsican' }),
    Object.freeze({ value: 'cr', label: 'Cree' }),
    Object.freeze({ value: 'hr', label: 'Croatian' }),
    Object.freeze({ value: 'cs', label: 'Czech' }),
    Object.freeze({ value: 'da', label: 'Danish' }),
    Object.freeze({ value: 'doi', label: 'Dogri' }),
    Object.freeze({ value: 'nl', label: 'Dutch' }),
    Object.freeze({ value: 'nl-BE', label: 'Dutch (Belgium)' }),
    Object.freeze({ value: 'nl-NL', label: 'Dutch (Netherlands)' }),
    Object.freeze({ value: 'dz', label: 'Dzongkha' }),
    Object.freeze({ value: 'en', label: 'English' }),
    Object.freeze({ value: 'en-AU', label: 'English (Australia)' }),
    Object.freeze({ value: 'en-CA', label: 'English (Canada)' }),
    Object.freeze({ value: 'en-IN', label: 'English (India)' }),
    Object.freeze({ value: 'en-IE', label: 'English (Ireland)' }),
    Object.freeze({ value: 'en-GB', label: 'English (United Kingdom)' }),
    Object.freeze({ value: 'en-US', label: 'English (United States)' }),
    Object.freeze({ value: 'eo', label: 'Esperanto' }),
    Object.freeze({ value: 'et', label: 'Estonian' }),
    Object.freeze({ value: 'ee', label: 'Ewe' }),
    Object.freeze({ value: 'fo', label: 'Faroese' }),
    Object.freeze({ value: 'fj', label: 'Fijian' }),
    Object.freeze({ value: 'fil', label: 'Filipino' }),
    Object.freeze({ value: 'fi', label: 'Finnish' }),
    Object.freeze({ value: 'fr', label: 'French' }),
    Object.freeze({ value: 'fr-BE', label: 'French (Belgium)' }),
    Object.freeze({ value: 'fr-CA', label: 'French (Canada)' }),
    Object.freeze({ value: 'fr-FR', label: 'French (France)' }),
    Object.freeze({ value: 'fr-CH', label: 'French (Switzerland)' }),
    Object.freeze({ value: 'ff', label: 'Fulah' }),
    Object.freeze({ value: 'gl', label: 'Galician' }),
    Object.freeze({ value: 'lg', label: 'Ganda' }),
    Object.freeze({ value: 'ka', label: 'Georgian' }),
    Object.freeze({ value: 'de', label: 'German' }),
    Object.freeze({ value: 'de-AT', label: 'German (Austria)' }),
    Object.freeze({ value: 'de-DE', label: 'German (Germany)' }),
    Object.freeze({ value: 'de-CH', label: 'German (Switzerland)' }),
    Object.freeze({ value: 'el', label: 'Greek' }),
    Object.freeze({ value: 'gn', label: 'Guarani' }),
    Object.freeze({ value: 'gu', label: 'Gujarati' }),
    Object.freeze({ value: 'guz', label: 'Gusii' }),
    Object.freeze({ value: 'ht', label: 'Haitian Creole' }),
    Object.freeze({ value: 'hak', label: 'Hakka Chinese' }),
    Object.freeze({ value: 'hak-TW', label: 'Hakka Chinese (Taiwan)' }),
    Object.freeze({ value: 'bgc', label: 'Haryanvi' }),
    Object.freeze({ value: 'ha', label: 'Hausa' }),
    Object.freeze({ value: 'haw', label: 'Hawaiian' }),
    Object.freeze({ value: 'iw', label: 'Hebrew' }),
    Object.freeze({ value: 'hi', label: 'Hindi' }),
    Object.freeze({ value: 'hi-Latn', label: 'Hindi (Latin)' }),
    Object.freeze({ value: 'ho', label: 'Hiri Motu' }),
    Object.freeze({ value: 'hu', label: 'Hungarian' }),
    Object.freeze({ value: 'is', label: 'Icelandic' }),
    Object.freeze({ value: 'ig', label: 'Igbo' }),
    Object.freeze({ value: 'id', label: 'Indonesian' }),
    Object.freeze({ value: 'ia', label: 'Interlingua' }),
    Object.freeze({ value: 'ie', label: 'Interlingue' }),
    Object.freeze({ value: 'iu', label: 'Inuktitut' }),
    Object.freeze({ value: 'ik', label: 'Inupiaq' }),
    Object.freeze({ value: 'ga', label: 'Irish' }),
    Object.freeze({ value: 'it', label: 'Italian' }),
    Object.freeze({ value: 'ja', label: 'Japanese' }),
    Object.freeze({ value: 'jv', label: 'Javanese' }),
    Object.freeze({ value: 'kl', label: 'Kalaallisut' }),
    Object.freeze({ value: 'kln', label: 'Kalenjin' }),
    Object.freeze({ value: 'kam', label: 'Kamba' }),
    Object.freeze({ value: 'kn', label: 'Kannada' }),
    Object.freeze({ value: 'ks', label: 'Kashmiri' }),
    Object.freeze({ value: 'kk', label: 'Kazakh' }),
    Object.freeze({ value: 'km', label: 'Khmer' }),
    Object.freeze({ value: 'ki', label: 'Kikuyu' }),
    Object.freeze({ value: 'rw', label: 'Kinyarwanda' }),
    Object.freeze({ value: 'tlh', label: 'Klingon' }),
    Object.freeze({ value: 'kok', label: 'Konkani' }),
    Object.freeze({ value: 'ko', label: 'Korean' }),
    Object.freeze({ value: 'ku', label: 'Kurdish' }),
    Object.freeze({ value: 'ky', label: 'Kyrgyz' }),
    Object.freeze({ value: 'lad', label: 'Ladino' }),
    Object.freeze({ value: 'lo', label: 'Lao' }),
    Object.freeze({ value: 'la', label: 'Latin' }),
    Object.freeze({ value: 'lv', label: 'Latvian' }),
    Object.freeze({ value: 'ln', label: 'Lingala' }),
    Object.freeze({ value: 'lt', label: 'Lithuanian' }),
    Object.freeze({ value: 'jbo', label: 'Lojban' }),
    Object.freeze({ value: 'dsb', label: 'Lower Sorbian' }),
    Object.freeze({ value: 'lu', label: 'Luba-Katanga' }),
    Object.freeze({ value: 'luo', label: 'Luo' }),
    Object.freeze({ value: 'lb', label: 'Luxembourgish' }),
    Object.freeze({ value: 'luy', label: 'Luyia' }),
    Object.freeze({ value: 'mk', label: 'Macedonian' }),
    Object.freeze({ value: 'mai', label: 'Maithili' }),
    Object.freeze({ value: 'mg', label: 'Malagasy' }),
    Object.freeze({ value: 'ms', label: 'Malay' }),
    Object.freeze({ value: 'ms-SG', label: 'Malay (Singapore)' }),
    Object.freeze({ value: 'ml', label: 'Malayalam' }),
    Object.freeze({ value: 'mt', label: 'Maltese' }),
    Object.freeze({ value: 'mni', label: 'Manipuri' }),
    Object.freeze({ value: 'mi', label: 'Māori' }),
    Object.freeze({ value: 'mr', label: 'Marathi' }),
    Object.freeze({ value: 'mas', label: 'Masai' }),
    Object.freeze({ value: 'mer', label: 'Meru' }),
    Object.freeze({ value: 'nan', label: 'Min Nan Chinese' }),
    Object.freeze({ value: 'nan-TW', label: 'Min Nan Chinese (Taiwan)' }),
    Object.freeze({ value: 'mxp', label: 'Mixe' }),
    Object.freeze({ value: 'lus', label: 'Mizo' }),
    Object.freeze({ value: 'mn', label: 'Mongolian' }),
    Object.freeze({ value: 'mn-Mong', label: 'Mongolian (Mongolian)' }),
    Object.freeze({ value: 'na', label: 'Nauru' }),
    Object.freeze({ value: 'nv', label: 'Navajo' }),
    Object.freeze({ value: 'ne', label: 'Nepali' }),
    Object.freeze({ value: 'pcm', label: 'Nigerian Pidgin' }),
    Object.freeze({ value: 'nd', label: 'North Ndebele' }),
    Object.freeze({ value: 'nso', label: 'Northern Sotho' }),
    Object.freeze({ value: 'no', label: 'Norwegian' }),
    Object.freeze({ value: 'oc', label: 'Occitan' }),
    Object.freeze({ value: 'or', label: 'Odia' }),
    Object.freeze({ value: 'om', label: 'Oromo' }),
    Object.freeze({ value: 'pap', label: 'Papiamento' }),
    Object.freeze({ value: 'ps', label: 'Pashto' }),
    Object.freeze({ value: 'fa', label: 'Persian' }),
    Object.freeze({ value: 'fa-AF', label: 'Persian (Afghanistan)' }),
    Object.freeze({ value: 'fa-IR', label: 'Persian (Iran)' }),
    Object.freeze({ value: 'pl', label: 'Polish' }),
    Object.freeze({ value: 'pt', label: 'Portuguese' }),
    Object.freeze({ value: 'pt-BR', label: 'Portuguese (Brazil)' }),
    Object.freeze({ value: 'pt-PT', label: 'Portuguese (Portugal)' }),
    Object.freeze({ value: 'pa', label: 'Punjabi' }),
    Object.freeze({ value: 'qu', label: 'Quechua' }),
    Object.freeze({ value: 'ro', label: 'Romanian' }),
    Object.freeze({ value: 'mo', label: 'Romanian (Moldova)' }),
    Object.freeze({ value: 'rm', label: 'Romansh' }),
    Object.freeze({ value: 'rn', label: 'Rundi' }),
    Object.freeze({ value: 'ru', label: 'Russian' }),
    Object.freeze({ value: 'ru-Latn', label: 'Russian (Latin)' }),
    Object.freeze({ value: 'sm', label: 'Samoan' }),
    Object.freeze({ value: 'sg', label: 'Sango' }),
    Object.freeze({ value: 'sa', label: 'Sanskrit' }),
    Object.freeze({ value: 'sat', label: 'Santali' }),
    Object.freeze({ value: 'sc', label: 'Sardinian' }),
    Object.freeze({ value: 'gd', label: 'Scottish Gaelic' }),
    Object.freeze({ value: 'sr', label: 'Serbian' }),
    Object.freeze({ value: 'sr-Cyrl', label: 'Serbian (Cyrillic)' }),
    Object.freeze({ value: 'sr-Latn', label: 'Serbian (Latin)' }),
    Object.freeze({ value: 'sh', label: 'Serbo-Croatian' }),
    Object.freeze({ value: 'sdp', label: 'Sherdukpen' }),
    Object.freeze({ value: 'sn', label: 'Shona' }),
    Object.freeze({ value: 'scn', label: 'Sicilian' }),
    Object.freeze({ value: 'sd', label: 'Sindhi' }),
    Object.freeze({ value: 'si', label: 'Sinhala' }),
    Object.freeze({ value: 'sk', label: 'Slovak' }),
    Object.freeze({ value: 'sl', label: 'Slovenian' }),
    Object.freeze({ value: 'so', label: 'Somali' }),
    Object.freeze({ value: 'nr', label: 'South Ndebele' }),
    Object.freeze({ value: 'st', label: 'Southern Sotho' }),
    Object.freeze({ value: 'es', label: 'Spanish' }),
    Object.freeze({ value: 'es-419', label: 'Spanish (Latin America)' }),
    Object.freeze({ value: 'es-MX', label: 'Spanish (Mexico)' }),
    Object.freeze({ value: 'es-ES', label: 'Spanish (Spain)' }),
    Object.freeze({ value: 'es-US', label: 'Spanish (United States)' }),
    Object.freeze({ value: 'su', label: 'Sundanese' }),
    Object.freeze({ value: 'sw', label: 'Swahili' }),
    Object.freeze({ value: 'ss', label: 'Swati' }),
    Object.freeze({ value: 'sv', label: 'Swedish' }),
    Object.freeze({ value: 'tl', label: 'Tagalog' }),
    Object.freeze({ value: 'tg', label: 'Tajik' }),
    Object.freeze({ value: 'ta', label: 'Tamil' }),
    Object.freeze({ value: 'tt', label: 'Tatar' }),
    Object.freeze({ value: 'te', label: 'Telugu' }),
    Object.freeze({ value: 'th', label: 'Thai' }),
    Object.freeze({ value: 'bo', label: 'Tibetan' }),
    Object.freeze({ value: 'ti', label: 'Tigrinya' }),
    Object.freeze({ value: 'tpi', label: 'Tok Pisin' }),
    Object.freeze({ value: 'tok', label: 'Toki Pona' }),
    Object.freeze({ value: 'to', label: 'Tongan' }),
    Object.freeze({ value: 'ts', label: 'Tsonga' }),
    Object.freeze({ value: 'tn', label: 'Tswana' }),
    Object.freeze({ value: 'tr', label: 'Turkish' }),
    Object.freeze({ value: 'tk', label: 'Turkmen' }),
    Object.freeze({ value: 'tw', label: 'Twi' }),
    Object.freeze({ value: 'uk', label: 'Ukrainian' }),
    Object.freeze({ value: 'hsb', label: 'Upper Sorbian' }),
    Object.freeze({ value: 'ur', label: 'Urdu' }),
    Object.freeze({ value: 'ug', label: 'Uyghur' }),
    Object.freeze({ value: 'uz', label: 'Uzbek' }),
    Object.freeze({ value: 've', label: 'Venda' }),
    Object.freeze({ value: 'vi', label: 'Vietnamese' }),
    Object.freeze({ value: 'vo', label: 'Volapük' }),
    Object.freeze({ value: 'vro', label: 'Võro' }),
    Object.freeze({ value: 'wa', label: 'Walloon' }),
    Object.freeze({ value: 'cy', label: 'Welsh' }),
    Object.freeze({ value: 'fy', label: 'Western Frisian' }),
    Object.freeze({ value: 'wal', label: 'Wolaytta' }),
    Object.freeze({ value: 'wo', label: 'Wolof' }),
    Object.freeze({ value: 'xh', label: 'Xhosa' }),
    Object.freeze({ value: 'yi', label: 'Yiddish' }),
    Object.freeze({ value: 'yo', label: 'Yoruba' }),
    Object.freeze({ value: 'zu', label: 'Zulu' }),
  ].sort((left, right) => left.label.localeCompare(right.label, 'en')),
);

export const YOUTUBE_AUDIO_LANGUAGE_OPTIONS: readonly YouTubeLanguageOption[] = Object.freeze([
  youTubeDefaultLanguageOption,
  ...[
    ...youTubeSharedLanguageOptions,
    Object.freeze({ value: 'zxx', label: 'Not applicable' }),
  ].sort((left, right) => left.label.localeCompare(right.label, 'en')),
]);

export const YOUTUBE_METADATA_LANGUAGE_OPTIONS: readonly YouTubeLanguageOption[] = Object.freeze([
  youTubeDefaultLanguageOption,
  ...youTubeSharedLanguageOptions,
]);

export function youtubeAudioLanguageOptionsFor(
  savedCode: string,
): readonly YouTubeLanguageOption[] {
  const code = savedCode.trim();
  if (code.length === 0 || YOUTUBE_AUDIO_LANGUAGE_OPTIONS.some((option) => option.value === code)) {
    return YOUTUBE_AUDIO_LANGUAGE_OPTIONS;
  }

  return [...YOUTUBE_AUDIO_LANGUAGE_OPTIONS, { value: code, label: `Language code: ${code}` }];
}

export function youtubeMetadataLanguageOptionsFor(
  savedCode: string,
): readonly YouTubeLanguageOption[] {
  const code = savedCode.trim();
  if (
    code.length === 0 ||
    YOUTUBE_METADATA_LANGUAGE_OPTIONS.some((option) => option.value === code)
  ) {
    return YOUTUBE_METADATA_LANGUAGE_OPTIONS;
  }

  return [...YOUTUBE_METADATA_LANGUAGE_OPTIONS, { value: code, label: `Language code: ${code}` }];
}
